# Generated by Django 5.1.4 on 2024-12-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CibilScoreCheck',
            fields=[
                ('cibilId', models.IntegerField(primary_key=True, serialize=False)),
                ('customerPanNo', models.IntegerField()),
                ('Score', models.IntegerField()),
                ('Cibil_status', models.CharField(max_length=250)),
                ('Remark', models.CharField(max_length=25)),
            ],
        ),
    ]
