# Generated by Django 5.1.4 on 2024-12-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('addressId', models.IntegerField(primary_key=True, serialize=False)),
                ('localHouseNo', models.CharField(max_length=250)),
                ('localArea', models.CharField(max_length=250)),
                ('localLandmark', models.CharField(max_length=250)),
                ('Localcity', models.CharField(max_length=250)),
                ('permanantHouseNo', models.CharField(max_length=250)),
                ('permanantArea', models.CharField(max_length=250)),
                ('permanantLandmark', models.CharField(max_length=250)),
                ('permananatCity', models.CharField(max_length=250)),
                ('Country', models.CharField(max_length=250)),
            ],
        ),
    ]
