# Generated by Django 5.1.4 on 2024-12-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guaranter',
            fields=[
                ('guaranterId', models.IntegerField(primary_key=True, serialize=False)),
                ('guranterName', models.CharField(max_length=250)),
                ('guaranterAddress', models.CharField(max_length=250)),
                ('guaranterRealtionshipwithcustomer', models.CharField(max_length=250)),
                ('guaranterMobileNo', models.CharField(max_length=250)),
                ('aadharCardNo', models.CharField(max_length=250)),
                ('jobDetails', models.CharField(max_length=250)),
            ],
        ),
    ]
