# Generated by Django 5.1.4 on 2025-01-05 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerId', models.IntegerField(primary_key=True, serialize=False)),
                ('customerName', models.CharField(max_length=250)),
                ('customerMobileno', models.IntegerField()),
                ('customerLoanAmount', models.IntegerField()),
                ('customerAge', models.IntegerField()),
                ('customerDateofBirth', models.CharField(max_length=252)),
                ('customerEmail', models.EmailField(max_length=254)),
                ('customerPancardno', models.CharField(max_length=250)),
                ('Address', models.TextField(max_length=300)),
                ('Bank', models.CharField(max_length=220)),
                ('Guaranter', models.CharField(max_length=250)),
                ('loandetails', models.CharField(max_length=250)),
                ('vehicalId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Vehicle.vehicle')),
            ],
        ),
    ]
