# Generated by Django 5.1.4 on 2025-01-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicalId', models.IntegerField(primary_key=True, serialize=False)),
                ('modelNo', models.CharField(max_length=250)),
                ('Dealer', models.CharField(max_length=250)),
                ('Price', models.CharField(max_length=250)),
                ('onRoadPrice', models.CharField(max_length=250)),
            ],
        ),
    ]
