# Generated by Django 5.1.4 on 2024-12-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentDetails',
            fields=[
                ('documentId', models.IntegerField(primary_key=True, serialize=False)),
                ('customerId', models.IntegerField()),
                ('Pancard', models.FileField(upload_to='documents/')),
                ('Aadharcard', models.FileField(upload_to='documents/')),
                ('Phote', models.FileField(upload_to='documents/')),
                ('Signature', models.FileField(upload_to='documents/')),
                ('Postdatedcheque', models.FileField(upload_to='documents/')),
                ('Thumb', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
