# Generated by Django 5.1.4 on 2024-12-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('enq_id', models.IntegerField(primary_key=True, serialize=False)),
                ('enq_name', models.CharField(max_length=120)),
                ('enqpancardno', models.CharField(max_length=240)),
                ('enq_mobileno', models.CharField(max_length=11)),
                ('enq_age', models.IntegerField()),
                ('enq_status', models.CharField(max_length=250)),
                ('enq_email', models.EmailField(max_length=254)),
                ('enq_vehicle_name', models.CharField(max_length=250)),
            ],
        ),
    ]
