# Generated by Django 5.1.4 on 2024-12-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('bankId', models.IntegerField(primary_key=True, serialize=False)),
                ('bankName', models.CharField(max_length=250)),
                ('accountNumber', models.CharField(max_length=250)),
                ('bankIfsc', models.CharField(max_length=250)),
                ('bankMicr', models.CharField(max_length=250)),
                ('bankAddress', models.CharField(max_length=250)),
            ],
        ),
    ]
